#!/bin/bash

SCRIPT_DIR=`dirname $BASH_SOURCE`
DATA=$SCRIPT_DIR/data

echo "Compiling returnval-ansi.c"
acc -S $DATA/returnval-ansi.c

echo "Compiling whole compiler."
acc -S "$DATA/otcc-ansi.c"

if (( "$(uname)" = "Linux" )) && (( "$(uname -m)" = "i686" )); then
	echo "Linux i686. Testing otcc-ansi.c"
	acc -R "$DATA/otcc-ansi.c" "$DATA/returnval.c"
	acc -R $DATA/otcc-ansi.c $DATA/otcc.c $DATA/returnval.c
fi

echo "Done with tests."
