#!/bin/sh
rm -f test-acc
cd ..
g++ -I../include acc.cpp disassem.cpp tests/main.cpp -g -ldl -o tests/test-acc
cd tests
if [ -x "test-acc" ]; then
  ./test-acc -S data/returnval-ansi.c

  if [ "$(uname)" = "Linux" ]; then
    if [ "$(uname -m)" = "i686" ]; then
      echo "Linux i686. Testing otcc-ansi.c"
      ./test-acc data/otcc-ansi.c data/returnval.c
      echo "Linux i686. Testing otcc-ansi.c data/otcc.c"
      ./test-acc data/otcc-ansi.c data/otcc.c data/returnval.c
    fi
  fi
fi
